source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxWebSocket_Example', :exclusive => true do
  pod "RxWebSocket", :path => "../"
  
  pod 'RxCocoa',    '~> 2.0'
end

target 'RxWebSocket_Tests', :exclusive => true do
  pod "RxWebSocket", :path => "../"
end
