platform :ios, 8.0

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'RxWebSocket_Example' do
    pod 'RxWebSocket', :path => '.'
    
    pod 'SwiftLint', '~> 0.23.1'

    target 'RxWebSocket_Tests' do
        inherit! :search_paths
    end
end
